name: CI Build

on:
    push:
        branches-ignore:
            - master
        tags:
            - v*
jobs:
    quality:
        name: Code Quality Checks
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Install Composer
              uses: MilesChou/composer-action@v1.0.1
              with:
                  args: install
            - name: Run Psalm Checks
              run: ./vendor/bin/psalm --output-format=compact --show-info=false

    test:
        name: Unit Tests
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Install Composer
              uses: MilesChou/composer-action@v1.0.1
              with:
                  args: install
            - name: Run PHPUnit
              run: ./vendor/bin/phpunit
